apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nexus-app
  template:
    metadata:
      labels:
        app: nexus-app
    spec:
      containers:
        - name: nexus-container
          image: 3.91.26.115:8082/devsecops-nexus:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: artifactory-registry-secret
